# Generated by Django 3.2.7 on 2021-10-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('short_descr', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='author_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='newcategory',
            options={'verbose_name_plural': 'New Categories'},
        ),
    ]
