# Generated by Django 3.2.7 on 2021-10-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211004_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='author',
            field=models.ManyToManyField(to='news.Author'),
        ),
    ]
