# Generated by Django 3.2.7 on 2021-10-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
