# Generated by Django 3.2.7 on 2021-10-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_new_sd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='sd',
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ManyToManyField(blank=True, to='news.Author'),
        ),
    ]
