# Generated by Django 3.2.7 on 2021-10-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20211006_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['id'], 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newcategory',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='author',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='author_images', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='short_descr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ManyToManyField(blank=True, to='news.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='new',
            name='header',
            field=models.CharField(max_length=64, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, upload_to='news_images', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='new',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='new',
            name='short_descr',
            field=models.CharField(blank=True, max_length=64, verbose_name='Краткое описание'),
        ),
    ]
